spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/db_food_delivery
    username: root
    password: 
  main:
    web-application-type: reactive
  application:
    name: DEMO

logging:
  level:
#    org.springframework.data.r2dbc: DEBUG
    com.dimata.service.general.billing : DEBUG

server:
  port: 8032